refactered register and login test
KarunAtreya/recipes pull request #13
Opened 2023-06-07 09:21 UTC by nirajacharya2

2023-06-08 09:10 UTC, PrajwolAmatya commented on tests/e2e/stepDefinitions/registerContext.js
> +  let featureError = await message.split(",");
```suggestion
  let actualErrorMessage = await registerPage.getErrorMessage(message);
  let expectedErrorMessage = await message.split(",");
```

2023-06-08 09:10 UTC, PrajwolAmatya commented on tests/e2e/stepDefinitions/registerContext.js
> +    `Expected to get ${featureError} but got diffrent errors: ${actualErrors}`
```suggestion
    actualErrorMessage,
    expectedErrorMessage,
    `Expected to get message "${expectedErrorMessage}" but got "${actualErrorMessage}"`
```

2023-06-09 07:17 UTC, PrajwolAmatya requested changes
Add description on the PR.

2023-06-09 07:17 UTC, PrajwolAmatya commented on tests/e2e/stepDefinitions/registerContext.js
> +  let errors = await registerPage.getSuccessMsg(succesMsg);
Better using meaningful variable names.
```suggestion
  const actualMessage = await registerPage.getSuccessMsg(succesMsg);
```

2023-06-12 10:28 UTC, PrajwolAmatya commented on tests/e2e/stepDefinitions/registerContext.js
> +  let expectedErrorMessage = await message.split(",");
```suggestion
  const actualErrorMessage = await registerPage.getErrorMessage(message);
  const expectedErrorMessage = await message.split(",");
```

2023-06-12 10:28 UTC, PrajwolAmatya commented on tests/e2e/stepDefinitions/registerContext.js
> +  let actualMessage = await registerPage.getSuccessMsg();
```suggestion
  const actualMessage = await registerPage.getSuccessMsg();
```

2023-06-12 10:32 UTC, grgprarup commented on tests/e2e/features/register.feature
> +        When the user sign up with username "<username>", password "<password>" and confirm password "<confirm password>"
```suggestion
        When the user signs up with following details
        | username        | <username>         |
        | password        | <password>         |
        |confirm_password | <confirm_password> |
```
We can easily modify the step when more parameters are added for the signup.

2023-06-12 11:07 UTC, PrajwolAmatya approved these changes

2023-06-12 11:08 UTC, merged